package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cuitCliente;
     private String domicilio;
     private String razonSocial;
     private Set contratos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int cuitCliente) {
        this.cuitCliente = cuitCliente;
    }
    public Cliente(int cuitCliente, String domicilio, String razonSocial, Set contratos) {
       this.cuitCliente = cuitCliente;
       this.domicilio = domicilio;
       this.razonSocial = razonSocial;
       this.contratos = contratos;
    }
   
    public int getCuitCliente() {
        return this.cuitCliente;
    }
    
    public void setCuitCliente(int cuitCliente) {
        this.cuitCliente = cuitCliente;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


