package com.mercado.resources;
// Generated 01-dic-2018 14:19:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private long cuitCliente;
    private String domicilio;
    private String razonSocial;
    private Set<Contrato> contratos = new HashSet(0);

    public Cliente() {
    }

    public Cliente(long cuitCliente) {
        this.cuitCliente = cuitCliente;
    }

    public Cliente(long cuitCliente, String domicilio, String razonSocial, Set contratos) {
        this.cuitCliente = cuitCliente;
        this.domicilio = domicilio;
        this.razonSocial = razonSocial;
        this.contratos = contratos;
    }

    public long getCuitCliente() {
        return this.cuitCliente;
    }

    public void setCuitCliente(long cuitCliente) {
        this.cuitCliente = cuitCliente;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public Set getContratos() {
        return this.contratos;
    }

    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }

    public Contrato crearContrato() {
        Contrato c = new Contrato();
        contratos.add(c);
        return c;
    }

    public Contrato crearContrato(int numero, Cliente cliente, Empleado empleado,
            Puesto puesto, Sesion sesion, Date fechaInicioContrato,
            Date fechaFinContrato) {
        Contrato c = new Contrato(numero, cliente, empleado, puesto, sesion,
                fechaInicioContrato, fechaFinContrato);
        contratos.add(c);
        return c;
    }

    public Contrato crearContrato(int numero, Cliente cliente, Empleado empleado,
            Puesto puesto, Sesion sesion, Double montoMensual, Date fechaInicioContrato,
            Date fechaFinContrato, Date fechaCancelacion) {
        Contrato c = new Contrato(numero, cliente, empleado, puesto, sesion,
                montoMensual, fechaInicioContrato, fechaFinContrato, fechaCancelacion);
        contratos.add(c);
        return c;
    }

    public Set cuantosContratosPeriodo(Date desde, Date hasta) {
        Set<Contrato> periodo = new HashSet<>(0);
        for (Contrato c : contratos) {
            if (c.getFechaCancelacion() != null && c.getFechaCancelacion().before(c.getFechaFinContrato())) {
                if (c.getFechaCancelacion().after(desde) && c.getFechaCancelacion().before(hasta)) {
                    periodo.add(c);
                }
            } else if (c.getFechaFinContrato().after(desde) && c.getFechaFinContrato().before(hasta)) {
                periodo.add(c);
            }
        }
        return periodo;
    }

    public int cuantosPuestosAlquila() {
        return contratos.size();
    }

    public boolean existeCliente(Cliente c) {
        return this.equals(c);
    }

    public Set quePuestosAlquila() {
        Set<Integer> puestos = new HashSet<>(0);
        for (Contrato c : contratos) {
            puestos.add(c.getPuesto().getNumero());
        }
        return puestos;
    }

    public boolean tieneContratoVigente() {
        boolean aviso = false;
        for (Contrato c : contratos) {
            if (c.estaVigente()) {
                aviso = true;
            }
        }
        return aviso;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (this.cuitCliente != other.cuitCliente) {
            return false;
        }
        return true;
    }
}
