package com.mercado.resources;
// Generated 01-dic-2018 14:19:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int numero;
     private Cliente cliente;
     private Empleado empleado;
     private Puesto puesto;
     private Sesion sesion;
     private Double montoMensual;
     private Date fechaInicioContrato;
     private Date fechaFinContrato;
     private Date fechaCancelacion;

    public Contrato() {
    }

	
    public Contrato(int numero, Cliente cliente, Empleado empleado, Puesto puesto, Sesion sesion, Date fechaInicioContrato, Date fechaFinContrato) {
        this.numero = numero;
        this.cliente = cliente;
        this.empleado = empleado;
        this.puesto = puesto;
        this.sesion = sesion;
        this.fechaInicioContrato = fechaInicioContrato;
        this.fechaFinContrato = fechaFinContrato;
    }
    public Contrato(int numero, Cliente cliente, Empleado empleado, Puesto puesto, Sesion sesion, Double montoMensual, Date fechaInicioContrato, Date fechaFinContrato, Date fechaCancelacion) {
       this.numero = numero;
       this.cliente = cliente;
       this.empleado = empleado;
       this.puesto = puesto;
       this.sesion = sesion;
       this.montoMensual = montoMensual;
       this.fechaInicioContrato = fechaInicioContrato;
       this.fechaFinContrato = fechaFinContrato;
       this.fechaCancelacion = fechaCancelacion;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Sesion getSesion() {
        return this.sesion;
    }
    
    public void setSesion(Sesion sesion) {
        this.sesion = sesion;
    }
    public Double getMontoMensual() {
        return this.montoMensual;
    }
    
    public void setMontoMensual(Double montoMensual) {
        this.montoMensual = montoMensual;
    }
    public Date getFechaInicioContrato() {
        return this.fechaInicioContrato;
    }
    
    public void setFechaInicioContrato(Date fechaInicioContrato) {
        this.fechaInicioContrato = fechaInicioContrato;
    }
    public Date getFechaFinContrato() {
        return this.fechaFinContrato;
    }
    
    public void setFechaFinContrato(Date fechaFinContrato) {
        this.fechaFinContrato = fechaFinContrato;
    }
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }




}


