package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private String apellido;
     private String dni;
     private Date fechaIngreso;
     private String legajo;
     private String nombre;
     private String nombreUsuario;
     private String password;
     private Set sesions = new HashSet(0);
     private Set contratos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int idEmpleado, String apellido, String dni, String legajo) {
        this.idEmpleado = idEmpleado;
        this.apellido = apellido;
        this.dni = dni;
        this.legajo = legajo;
    }
    public Empleado(int idEmpleado, String apellido, String dni, Date fechaIngreso, String legajo, String nombre, String nombreUsuario, String password, Set sesions, Set contratos) {
       this.idEmpleado = idEmpleado;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaIngreso = fechaIngreso;
       this.legajo = legajo;
       this.nombre = nombre;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.sesions = sesions;
       this.contratos = contratos;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(String legajo) {
        this.legajo = legajo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getSesions() {
        return this.sesions;
    }
    
    public void setSesions(Set sesions) {
        this.sesions = sesions;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


