package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lectura generated by hbm2java
 */
public class Lectura  implements java.io.Serializable {


     private int idLectura;
     private Contrato contrato;
     private Puesto puesto;
     private Date fechaCaptura;
     private String lectura;

    public Lectura() {
    }

	
    public Lectura(int idLectura, Puesto puesto) {
        this.idLectura = idLectura;
        this.puesto = puesto;
    }
    public Lectura(int idLectura, Contrato contrato, Puesto puesto, Date fechaCaptura, String lectura) {
       this.idLectura = idLectura;
       this.contrato = contrato;
       this.puesto = puesto;
       this.fechaCaptura = fechaCaptura;
       this.lectura = lectura;
    }
   
    public int getIdLectura() {
        return this.idLectura;
    }
    
    public void setIdLectura(int idLectura) {
        this.idLectura = idLectura;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Date getFechaCaptura() {
        return this.fechaCaptura;
    }
    
    public void setFechaCaptura(Date fechaCaptura) {
        this.fechaCaptura = fechaCaptura;
    }
    public String getLectura() {
        return this.lectura;
    }
    
    public void setLectura(String lectura) {
        this.lectura = lectura;
    }




}


