package com.mercado.resources;
// Generated 29-nov-2018 14:41:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lectura generated by hbm2java
 */
public class Lectura  implements java.io.Serializable {


     private int idLectura;
     private Puesto puesto;
     private Date fechaCaptura;
     private Double lectura;

    public Lectura() {
    }

	
    public Lectura(int idLectura, Puesto puesto) {
        this.idLectura = idLectura;
        this.puesto = puesto;
    }
    public Lectura(int idLectura, Puesto puesto, Date fechaCaptura, Double lectura) {
       this.idLectura = idLectura;
       this.puesto = puesto;
       this.fechaCaptura = fechaCaptura;
       this.lectura = lectura;
    }
   
    public int getIdLectura() {
        return this.idLectura;
    }
    
    public void setIdLectura(int idLectura) {
        this.idLectura = idLectura;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Date getFechaCaptura() {
        return this.fechaCaptura;
    }
    
    public void setFechaCaptura(Date fechaCaptura) {
        this.fechaCaptura = fechaCaptura;
    }
    public Double getLectura() {
        return this.lectura;
    }
    
    public void setLectura(Double lectura) {
        this.lectura = lectura;
    }




}


