package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PrecioAlquile generated by hbm2java
 */
public class PrecioAlquile  implements java.io.Serializable {


     private int idPrecioAlquiler;
     private Dimension dimension;
     private Puesto puesto;
     private Sector sector;
     private TipoPuest tipopuesto;
     private BigDecimal precio;
     private Date fechaVigencia;
     private String precioAlquilercol;

    public PrecioAlquile() {
    }

	
    public PrecioAlquile(int idPrecioAlquiler, Dimension dimension, Puesto puesto, Sector sector, TipoPuest tipopuesto, BigDecimal precio) {
        this.idPrecioAlquiler = idPrecioAlquiler;
        this.dimension = dimension;
        this.puesto = puesto;
        this.sector = sector;
        this.tipopuesto = tipopuesto;
        this.precio = precio;
    }
    public PrecioAlquile(int idPrecioAlquiler, Dimension dimension, Puesto puesto, Sector sector, TipoPuest tipopuesto, BigDecimal precio, Date fechaVigencia, String precioAlquilercol) {
       this.idPrecioAlquiler = idPrecioAlquiler;
       this.dimension = dimension;
       this.puesto = puesto;
       this.sector = sector;
       this.tipopuesto = tipopuesto;
       this.precio = precio;
       this.fechaVigencia = fechaVigencia;
       this.precioAlquilercol = precioAlquilercol;
    }
   
    public int getIdPrecioAlquiler() {
        return this.idPrecioAlquiler;
    }
    
    public void setIdPrecioAlquiler(int idPrecioAlquiler) {
        this.idPrecioAlquiler = idPrecioAlquiler;
    }
    public Dimension getDimension() {
        return this.dimension;
    }
    
    public void setDimension(Dimension dimension) {
        this.dimension = dimension;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }
    public TipoPuest getTipopuesto() {
        return this.tipopuesto;
    }
    
    public void setTipopuesto(TipoPuest tipopuesto) {
        this.tipopuesto = tipopuesto;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFechaVigencia() {
        return this.fechaVigencia;
    }
    
    public void setFechaVigencia(Date fechaVigencia) {
        this.fechaVigencia = fechaVigencia;
    }
    public String getPrecioAlquilercol() {
        return this.precioAlquilercol;
    }
    
    public void setPrecioAlquilercol(String precioAlquilercol) {
        this.precioAlquilercol = precioAlquilercol;
    }




}


