package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int idPuesto;
     private Estado estado;
     private Integer numero;
     private Set lecturas = new HashSet(0);
     private Set precioalquilers = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(int idPuesto, Estado estado) {
        this.idPuesto = idPuesto;
        this.estado = estado;
    }
    public Puesto(int idPuesto, Estado estado, Integer numero, Set lecturas, Set precioalquilers) {
       this.idPuesto = idPuesto;
       this.estado = estado;
       this.numero = numero;
       this.lecturas = lecturas;
       this.precioalquilers = precioalquilers;
    }
   
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Set getLecturas() {
        return this.lecturas;
    }
    
    public void setLecturas(Set lecturas) {
        this.lecturas = lecturas;
    }
    public Set getPrecioalquilers() {
        return this.precioalquilers;
    }
    
    public void setPrecioalquilers(Set precioalquilers) {
        this.precioalquilers = precioalquilers;
    }




}


