package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private int idSector;
     private String nombre;
     private String descripcion;
     private Set precioalquilers = new HashSet(0);

    public Sector() {
    }

	
    public Sector(int idSector, String nombre) {
        this.idSector = idSector;
        this.nombre = nombre;
    }
    public Sector(int idSector, String nombre, String descripcion, Set precioalquilers) {
       this.idSector = idSector;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioalquilers = precioalquilers;
    }
   
    public int getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(int idSector) {
        this.idSector = idSector;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPrecioalquilers() {
        return this.precioalquilers;
    }
    
    public void setPrecioalquilers(Set precioalquilers) {
        this.precioalquilers = precioalquilers;
    }




}


