package com.mercado.resources;
// Generated 27-nov-2018 15:59:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopuesto generated by hbm2java
 */
public class Tipopuesto  implements java.io.Serializable {


     private int idTipoPuesto;
     private String nombre;
     private String descripcion;
     private Set precioalquilers = new HashSet(0);

    public Tipopuesto() {
    }

	
    public Tipopuesto(int idTipoPuesto, String nombre) {
        this.idTipoPuesto = idTipoPuesto;
        this.nombre = nombre;
    }
    public Tipopuesto(int idTipoPuesto, String nombre, String descripcion, Set precioalquilers) {
       this.idTipoPuesto = idTipoPuesto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioalquilers = precioalquilers;
    }
   
    public int getIdTipoPuesto() {
        return this.idTipoPuesto;
    }
    
    public void setIdTipoPuesto(int idTipoPuesto) {
        this.idTipoPuesto = idTipoPuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPrecioalquilers() {
        return this.precioalquilers;
    }
    
    public void setPrecioalquilers(Set precioalquilers) {
        this.precioalquilers = precioalquilers;
    }




}


